In [1]:
#neural networks with 3 inputs
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]

bias = 2

outputs = (inputs[0] * weights[0] + inputs[1]* weights[1] + inputs[2] * weights[2]) +bias
print(outputs)

2.3


In [2]:
#now lets say i wanna add neuron with 4 inputs
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

outputs = (inputs[0] * weights[0] + inputs[1]* weights[1] + inputs[2] * weights[2] + inputs[3] * weights[3]) +bias

print(outputs)


4.8


In [3]:
#Now calculating a layer of neurons

inputs = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0]]

In [3]:
import numpy as np

In [5]:
#now using numpy

import numpy as np
inputs =[1.0,2.0,3.0,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2.0
outputs = np.dot(weights,inputs) + bias
print(outputs)

4.8


In [6]:
inputs =[1.0,2.0,3.0 ,2.5]
weights =[[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

biases = [2.0,3.0,0.5]

#toh jab matrix aa jaata toh toh direct 
#np.dot(matrix,vector) karte
#toh matrcx hai weihgts ka
#aur aise kyu karte yuki dot prodcut of weights, inputs is what we need
#the dot product of (inputs, weights) is meaningless
#agr matrix hoga toh 
#so we take matrix firsst

outputs = np.dot(weights,inputs) + biases

#ye biases direct add hojayega kyuki matrix same size ka aeygea

print(outputs)


[4.8   1.21  2.385]


In [7]:
#Now for the batches of inputs
inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2,0.8,-0.5,1.0],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]

biases = [2.0,3.0,0.5]

outputs = np.dot(inputs,np.array(weights).T)+ biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [1]:
#now creating a class for desne layer class

In [2]:
#this will give us a template on how to implement the whole class


In [3]:
#by doing this we can just directly call an instant and run the coed


In [8]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

#Now for creation of the layer
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        #this init function is called automatically whenever the
        #instant of this Layer_Dense class is created
        # now the function of this init function is to intialise the weights of the layer
        # and initailise the biases
        self.weights = 0.01 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
        #ham starting mei saare biases ko same initialisation dedete 0s se
        #but moving forward inka bias differently update hota based on the gradients
        
    def forward(self,inputs):
        #calculating the output values
        self.output = np.dot(inputs,self.weights) + self.biases
        
#ab create karte hai dataset
X, y = spiral_data(samples = 100, classes =3)
#ye hamei 100 points ke teen spiral dega as classes are 3 aur har spiral will have 100 points in it

#Now creating a dense layer wiht 2 input features and 3 neurons

dense_layer1 = Layer_Dense(2,3)


#ab layer bangyii toh uska output nikaal dete hai
dense_layer1.forward(X)

#ab X hamara input hai aur y is the thing we want to predict here
#so thats why we pass dense_layer1.forward(X) only X is passed here thats why

#now to check output for some samples
print(dense_layer1.output[:8])


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]
 [-3.5430698e-04  3.5025488e-04 -2.3363481e-04]
 [-8.9267001e-04  1.0767876e-03 -1.9453237e-04]
 [-9.3350781e-04  1.0723802e-03 -3.1227397e-04]]


In [15]:
dense_layer2 = Layer_Dense(2,5)
X1,y1 = spiral_data(samples=100, classes = 5)

dense_layer2.forward(X1)

print(dense_layer2.output[:6])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-1.70334781e-04  3.30507901e-05  4.51893320e-05  2.80951153e-05
   6.54213000e-05]
 [-4.36228729e-04  8.66227783e-05 -1.74717206e-05  1.67510298e-04
   4.94227424e-05]
 [-6.38892991e-04  1.26491053e-04 -3.43322569e-07  2.27221681e-04
   9.47710214e-05]
 [-9.04552580e-04  1.80725969e-04 -1.10736255e-04  4.00796242e-04
   3.64095868e-05]
 [-1.14665646e-03  2.30427613e-04 -2.29891331e-04  5.72288234e-04
  -3.32274030e-05]]


In [16]:
A = [[1,2,3],[4,5,6],[7,8,9]]

print(np.sum(A))

45


In [17]:
print(np.max(A,axis=1))

[3 6 9]


In [19]:
print(np.max(A,axis=1,keepdims=True).shape)

(3, 1)


In [21]:
print(np.max(A,axis=1).shape)

(3,)


In [24]:
#dekh keepdims = true karne aur na karne mei
#Agr keep dims = true nahi krenge toh ye return karta hai ek 1 dimensional array
#jo ki yaha pe return kar raha hai abhi in the case of keepdims= true pe
#true rakhne pe wo matrix ka shape maintain krta hai and will be returning the 3,1

In [25]:
np.sum(A,axis=0)

array([12, 15, 18])

In [34]:
np.max(A,axis=0)

array([7, 8, 9])

In [35]:
print(np.max(A,axis=0,keepdims=True).shape)

(1, 3)


In [23]:
#okay so this is done now we will be working with the actvation functions

In [26]:
#implementing Activation function Relu
import numpy as np
inputs = [0,2,-1,3.3,-2.7 ,1.1,2.2,-100]
#ye tere inputs hogye 
#ab tuje pata hai relu function hota max(0,x)
#where x is your input theeke
outputs = np.maximum(0,inputs)
print(outputs)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [27]:
#now creating a reusable class for the relu function
class Activation_ReLU:
    #ab forward pass iska 
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)        
    

In [28]:
#now implementing softmax
inputs = [[1,2,3,2.5],
          [2,5,-1,2],
          [-1.5,2.7,3.3,-0.8]]

#So first we will be getting unnormalised probabilites
exp_values = np.exp(inputs - np.max(inputs,axis =1,keepdims =True))

#aur yaha pe subtract kyu krte taaki overflow na hojaaye
#kyuki when we take exponent the data overflows so to avoid it
#we subtract by the maximal value
#this will give us negative values andatleast one zero
#aur exponent of -ve values is small
#so overflow is solved

#now calculating probabilites
probabilities = exp_values / np.sum(exp_values,axis=1,keepdims=True)
print(probabilities)

#ye hamei probabilities dedega


#ab to cross check the sum of the probabilites should be 1
#but row wise check karenge
#kyuki inputs bactches mei aare
#aur ek batch ek row hai
print(np.sum(probabilities,axis=1))

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]
[1. 1. 1.]


In [29]:
#Now creating softmax activation function class
class Activation_Softmax:
    def forward(self,inputs):
        #Get normalised probabilites
        exp_values = np.exp(inputs - np.max(inputs,axis =1,keepdims =True))
        
        probabilities = exp_values / np.sum(exp_values,axis =1 , keepdims = True)
        self.output = probabilities

In [30]:
X,y = spiral_data(samples=100,classes =3)
#this will create our dataset which will have 3 spirals and each will be having a sample of 100 pts

#now coming to creating a dense layer we will be having a dense layer with 2 input features and 3 outputs

dense1 = Layer_Dense(2,3)


activation1 = Activation_ReLU()


#Now creating a second dense layer which will be having the output of the first layer and will be generating the output as 3 outputs

dense2 =  Layer_Dense(3,3)

#now the activation function here would be spftmnax
#since we need classification

activation2 = Activation_Softmax()

#Now we will be making a forward pass of our 1 st layer

dense1.forward(X)

#Now we will be taking the forward pass of the activation function 
#this will be taking the output of the first layer nad then it will be passed to the activation function
activation1.forward(dense1.output)

#why we add activation function to the outputs to the first layer
#since we need to add non linearity and this will help in capturing the complex elements of our layer


#Now the second layer will be taking the outputs of the activation function from the 1st layer
dense2.forward(activation1.output)

#Now we will be making forward pass throught activation function
#it will take the output of the second dense layer
activation2.forward(dense2.output)

print(activation2.output[:5])







[[0.33333334 0.33333334 0.33333334]
 [0.33333305 0.33333322 0.33333376]
 [0.33333233 0.333333   0.33333468]
 [0.33333322 0.33333325 0.3333335 ]
 [0.33333117 0.33333263 0.3333362 ]]


In [ ]:
#Building up the cross entropy loss function building blocks

In [ ]:
#hampe kya hoga dataset se softmax_outputs aayenge
#ham maan re hai abhi ki hamara data 3 class mei categorise krre hai
#ham abhi jo ki hai red green blue
#aur fir ham isme cross entropy loss calculate karenge
#jiska formula toh categorised standard hai
#but 
softmax_outputs = np.array([[0.7,0.1,0.2],
                            [0.1,0.5,0.4],
                            [0.02,0.9,0.08]])

#yaha pe har ek row ek input of data bata ra hai hamei
#for example 0.7 , 0.1, 0.2
#ye batara the confidence of being red is 0.7  and of green is 0.1 and of the blue is 0.2
#aur har ek row hamara har ek dataset ke barei mei bata ta hai


class_targets = [0,1,1]
#ab class targets hai hamarei true prediction
#yaha pe 0 is for red 1 is for green 2 is for blue
#toh true prediction hai jo matlb true data mei 1st data mei aara hai
#red and then green and green respectively

print(softmax_outputs[[0,1,2],class_targets])

#ab ye print statement aise kaam karta ki
#softamax_ouptuts matrix pe hamne rows define kardi [0,1,2]
#but jo column hai wo ye lera hai class targets se
#mtlb [0,1,1]
#toh combination bnre hia [0,0], [1,1],[2,1]
#jo ki max probabale answer dega softmax outputs se


[0.7 0.5 0.9]


In [1]:
#ab agr hamara data one hot encoded hai toh
#ham kaise extract karenge relevant predictions


In [4]:
#one hot encoding mei sirf 1 correct waale pe hota
#aur baaki sab 0 hote hai
y_true_check = np.array([
    [0,1,0],
    [1,0,0],
    [0,0,1]
])

y_pred_clipped_check = np.array([
    [0.2,0.7,0.1],
    [0.8,0.1,0.1],
    [0.1,0.2,0.7]
])



To calculate loss using one hot encoded method
ham phle element wise multiplication krte
fir ham sum karte along the column
and then take -ve log 
and then take mena of the final

In [7]:
A = y_true_check * y_pred_clipped_check

In [9]:
B = np.sum(A,axis =1)

In [13]:
C = -np.log(B)


In [14]:
D = np.mean(C)